[project]
name = "fs25-vehicle-sorter"
version = "0.1.0"
description = "Farming Simulator 2025 Vehicle Sorter"
requires-python = ">=3.12"
dependencies = [
    "FreeSimpleGUI~=5.2.0",
    "pyinstaller~=6.16.0",
]
